stages:
  train_test_split:
    cmd: python ./src/data/train_test_split.py
    deps:
    - ./data/raw_data/raw.csv
    - ./src/data/train_test_split.py
    outs:
    - ./data/processed_data/X_test.csv
    - ./data/processed_data/X_train.csv
    - ./data/processed_data/y_test.csv
    - ./data/processed_data/y_train.csv
  normalize:
    cmd: python ./src/data/normalize.py --force
    deps:
    - ./data/processed_data/X_test.csv
    - ./data/processed_data/X_train.csv
    - ./src/data/normalize.py
    outs:
    - ./data/processed_data/X_test_scaled.csv
    - ./data/processed_data/X_train_scaled.csv
